### PR TITLE
Upgrade UI kit to v1.7.2

### PR DESCRIPTION
**Pull request by maxious**
and image assets from vendor can be used in app asset pipeline

screen shot 2016-08-02 at 10 55 27 am

### CODE REVIEW

**Comment by simonschwartz** [comment]
LGTM

**Comment by micapam** [comment]
content_blocks in schema.rb ?

**Comment by ltankey** [comment]
You have to drop content_blocks from your prod dump

**Comment by ltankey** [comment]
LGTM

**Comment by maxious** [comment]
dropped it.

**Comment by maxious** [comment]
rebase

**Pull request merged**
