### PR TITLE
Remove check on CONTENT_ANALYSIS_BASE_URL

### PR DESCRIPTION
**Pull request by bjgordon**

### CODE REVIEW

**Comment by tessereth** [comment]
LGTM

**Comment by ltankey** [comment]
Perhaps an opportunity to remove the helper outright. I suspect when we revisit this, we'd approach it differently anyway.

**Comment by bjgordon** [comment]
Ok will do

**Comment by bjgordon** [comment]
This has lead to complete removal of CAS. Will open a new PR and branch...

**Pull request closed without merging**
