### PR TITLE
[SITES-497] Update footer markup to match ui-kit

### LINKED ISSUE #302: Footer layout/markup not matching latest UI Kit
It looks like the footer markup needs to be updated to take on latest UI Kit styles:

image

Here's the markup from the example page in the screenshot above.

https://github.com/AusDTO/gov-au-ui-kit/blob/develop/examples/index.html#L522

### PR DESCRIPTION
**Pull request by tessereth**
Fixes #302. @petronbot, can you please review this?

### CODE REVIEW

**Comment by coderdan** [comment]
LGTM

**Comment by tessereth** [comment]
please update changelog post 0.8.1 release

**Comment by micapam** [comment]
LGTM

**Comment by tessereth** [comment]
@klepas It does have that role. It just doesn't appear in the diff because it's in a part of the file that's unchanged.

**Comment by klepas** [comment]
My bad. (:

**Pull request merged**
