### PR TITLE
Remove rails_12factor gem

### PR DESCRIPTION
**Pull request by bjgordon**
Not needed in rails 5: https://github.com/heroku/rails_12factor#rails-5-and-beyond

### CODE REVIEW

**Comment by maxious** [comment]
Do we also need to add the logging lines? https://github.com/heroku/rails_12factor#rails-5-and-beyond

(I don't think we're using Apache/NGINX)

**Comment by bjgordon** [comment]
@maxious Those lines were already in `production.rb`. However you made me look closer, and we were also including `rails_serve_static_assets` gem which is not needed, I've removed.

**Comment by maxious** [comment]
I think we *do* need rails_serve_static_assets because we're not using NGINX/Apache. Perhaps could test cf push somewhere with the gem removed?

**Comment by bjgordon** [comment]
The README is a little unclear, but I'd thought that's what `config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?` in `production.rb` did. We'd need to define that env var though. I'll test it.

**Comment by bjgordon** [comment]
Worked for me with staging -green. As @maxious mentioned offline, the build-pack will set that env var.

**Comment by tessereth** [comment]
LGTM

**Comment by maxious** [comment]
LGTM

**Pull request merged**
