### PR TITLE
[SITES-550] Fixed missing anchor link on link beneath related topics

### PR DESCRIPTION
**Pull request by micapam**
SITES-550

### CODE REVIEW

**Comment by tessereth** [comment]
LGTM. But as an aside, you need to add the SITES-xxx to either your branch name or the PR name for it to automatically get linked to JIRA.

**Comment by ltankey** [comment]
LGTM

**Comment by maxious** [comment]
LGTM

**Comment by maxious** [comment]
"471 examples, 0 failures" circleci failing to report.

**Pull request merged**
