### PR TITLE
[SITES-508 SITES-521 SITES-519 SITES-192] Release notes to CHANGELOG re: prod email

### PR DESCRIPTION
**Pull request by freshtonic**
For the following Jira tickets:

    SITES-508
    SITES-521
    SITES-519
    SITES-192

### CODE REVIEW

**Comment by maxious** [comment]
LGTM also include my missing log entry

**Comment by freshtonic** [comment]
@maxious ???

**Comment by bjgordon** [comment]
LGTM

**Comment by ltankey** [comment]
Just as an aside - you have to include the ticket ids in the PR name to have it automatically move in Jira.

**Pull request merged**
