### PR TITLE
Times dates content update

### PR DESCRIPTION
**Pull request by simonschwartz**
This PR simply adds the new content pages for Times and Dates that @nicholasgkdto produced

### CODE REVIEW

**Comment by tessereth** [comment]
We really need to fix the way we do times and dates. But until then, this LGTM.

**Comment by coderdan** [comment]
So much debt 💯 :( But yeah for now LGTM

**Comment by tessereth** [comment]
please update changelog post 0.8.1 release

**Comment by micapam** [comment]
I tried reading this PR but it was too long. LBTM 

;)

**Comment by maxious** [comment]
Now has conflicts :(

**Pull request merged**
