### PR TITLE
[SITES-516] Fix check for whether partial exists

### PR DESCRIPTION
**Pull request by tessereth**

### CODE REVIEW

**Comment by micapam** [comment]
LGTM

**Comment by bjgordon** [comment]
LGTM

**Comment by ltankey** [comment]
LGTM

**Comment by bjgordon** [comment]
In #259 which lead to SITES-516, michael asked for the form labels to be "short summary" and "long summary"... Should we fix it in this PR? Currently what is displayed in the form: 
image

**Comment by bjgordon** [comment]
LGTM

**Pull request merged**
