### PR TITLE
SITES-630 Timeout sessions after 90 minutes idle

### PR DESCRIPTION
**Pull request by maxious**
Use built-in devise functionality for this.

### CODE REVIEW

**Comment by ltankey** [comment]
LGTM

**Comment by tessereth** [comment]
LGTM though if you can figure out a way to test it, that would be great.

**Comment by maxious** [comment]
Hmm devise has https://github.com/plataformatec/devise/blob/master/test/models/timeoutable_test.rb

**Comment by tessereth** [comment]
Fair call. Makes sense.

**Comment by maxious** [comment]
rebased

**Pull request merged**
