### PR TITLE
Update section news listing style GOVAU-468

### PR DESCRIPTION
**Pull request by simonschwartz**
This PR updates the news listing style on Department, Minister and Topic sections.

This closes GOVAU-468

news-listing

### CODE REVIEW

**Comment by tessereth** [comment]
LGTM

**Comment by ltankey** [comment]
Do we have a screenshot of the affect of this PR on the news index with filter?

**Comment by simonschwartz** [comment]
@ltankey This PR doesn't affect the news index with filter page

**Comment by ltankey** [comment]
Ahh ok cool

**Pull request merged**
