### PR TITLE
SITES-495 Navigation items at all levels are not using Design Guide styles to highlight the current page

### PR DESCRIPTION
**Pull request by streetdaddy**
Updated to match the ui-kit spec class names for current nav item:

http://gov-au-ui-kit-staging.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-2-local-navigation

nb. I made this change content blind because I got stuck trying to log in to localhost and create the required page hierarchy 😞

### CODE REVIEW

**Comment by ltankey** [comment]
@streetdaddy is this WIP?

**Comment by streetdaddy** [comment]
@tessereth updated the nav template logic.

**Comment by tessereth** [comment]
We also need to apply the `is-active` class to all parents of the current node. Would you be okay with me making my own PR or would you rather I explain how to find the parents of a node so you can do it?

**Comment by streetdaddy** [comment]
Outdone by #446

**Pull request closed without merging**
