### PR TITLE
WIP SITES-685 Performance on news#index

### PR DESCRIPTION
**Pull request by bjgordon**
Still need to improve behaviour of `related_sections`

### CODE REVIEW

**Comment by bjgordon** [comment]
The page time is improved but still not that great - locally down from around 4.5s to 2.5s using a prod db dump.
In `/newrelic` this change has reduced the number of database queries of `/news` request from 457 to 336. The remainder are little queries for each related_sections partial, but I havent been able to reduce that. Open to ideas.

**Comment by freshtonic** [comment]
@bjgordon this is using production Rails config locally right?

**Comment by bjgordon** [comment]
@freshtonic actually no. I was just interested in relativele performance change so didnt think itd matter... ?

**Comment by freshtonic** [comment]
@bjgordon benchmarking in development mode is not going to tell you anything useful IMHO.  The overheads are quite large & some internal caching is disabled.

**Comment by freshtonic** [comment]
@bjgordon basically, I wouldn't count on dev mode to have the same relative performance change characteristics as prod mode.

**Comment by bjgordon** [comment]
@freshtonic Ok I'll test again in prod mode.

**Comment by bjgordon** [comment]
In production mode before the change it takes around 1.5s with 180 db hits, after the change around 1s with 80 db hits.

**Comment by tessereth** [comment]
Should this same change be applied to the `/:section/news` pages as well?

**Comment by freshtonic** [comment]
Is something hitting that `news_articles` helper in a loop to load the data?  80 database hits is way too many. "around 5 to 7" database hits to build a page is a reasonable number. That's normally enough to load the user & roles and a the resources to load the page.

**Comment by bjgordon** [comment]
@freshtonic I think the issue is in `_related_sections.html.haml`, each news_article's related_sections and home_node is two separate queries.

**Comment by freshtonic** [comment]
@bjgordon so the solution to this is to front load everything we need and not invoke helpers to load additional data. Judicious use of `:includes` is key.

**Comment by tessereth** [comment]
Update changelog post 1.3.0 release

**Comment by bjgordon** [comment]
Have tried moving related_sections to the model, but can't `.includes` it as it's instance dependent. Also tried getting rid of the use of the decorator, but that increased the db hits as filtering is now done in db rather than in memory, and didn't help with preloading, so should probably revert that. Handing this over to @freshtonic to take a look at.

**Comment by freshtonic** [comment]
Replaced by https://github.com/AusDTO/gov-au-beta/pull/491

**Pull request closed without merging**
