### PR TITLE
SITES-624 Allow optional role and organisation feedback fields

### PR DESCRIPTION
**Pull request by coderdan**

### CODE REVIEW

**Comment by tessereth** [comment]
LGTM

**Comment by bjgordon** [comment]
The requirement is that these fields are required. The bug report was that the form displayed them as required, but validation was not failing if they were empty.

**Comment by coderdan** [comment]
Right, understood @bjgordon. I'll change it.

**Comment by maxious** [comment]
LGTM

**Comment by ltankey** [comment]
LGTM, but is there an associated jira ticket we could put into the title of the PR?

**Comment by coderdan** [comment]
Bump LGTM

**Pull request merged**
