### PR TITLE
fix rendering of abstract on base node template

### PR DESCRIPTION
**Pull request by ltankey**
Fix the metatag wrapping for the description based on short_summary of a node.

### CODE REVIEW

**Comment by micapam** [comment]
The changes LGTM. Though I'm not clear on your description - not sure what you mean by Minister? Isn't Minister a Section rather than a Node...?

**Comment by ltankey** [comment]
@micapam I'm not clear on this now - I thought I tested earlier and this fixed it, but now I've realised it's redundant.

The necessary templates *should* already have the required summaries. I'll investigate further.

**Comment by ltankey** [comment]
OK the changes to the template are in develop and will be merged in next release.

This PR now officially just fixes the metatag wrapping.

**Comment by tessereth** [comment]
changelog?

**Comment by ltankey** [comment]
The metadata bug was introduced in this change (it currently renders out the short_summary, yuck!). Do you think we need to record the fact we now have a metadata tag? Happy to put it in.

**Comment by tessereth** [comment]
right. LGTM.

**Pull request merged**
