### PR TITLE
SITES-604 Upgrade rails and remove instances of permit! mass assignment

### PR DESCRIPTION
**Pull request by maxious**
"Rails 5.0.0.1, 4.2.7.1, and 3.2.22.3 have been released! These release contain important security fixes, so please upgrade when you can." http://weblog.rubyonrails.org/2016/8/11/Rails-5-0-0-1-4-2-7-2-and-3-2-22-3-have-been-released/

Added _params private methods and used where appropriate. Handles the nested values of child ordering and other metadata options.

### CODE REVIEW

**Comment by tessereth** [comment]
Changelog? Otherwise LGTM.

**Comment by tessereth** [comment]
Update changelog post 1.1.0 release

**Comment by bjgordon** [comment]
LGTM

**Comment by maxious** [comment]
rebased

**Pull request merged**
